# Generated by Django 5.0.6 on 2024-06-15 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('autos', 'Autos'), ('motos', 'Motos'), ('camionetas', 'Camionetas'), ('camiones', 'Camiones'), ('buses', 'Buses'), ('trailers', 'Trailers'), ('agricolas', 'Agricolas'), ('acuaticos', 'Acuaticos'), ('otro', 'Otro')], default='autos', max_length=15)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('anioFabricacion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('telefonoVendedor', models.CharField(max_length=20)),
                ('emailVendedor', models.EmailField(max_length=254)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendedor', '-fechaPublicacion'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='App.vehiculo')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
