# Generated by Django 5.0.6 on 2024-06-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_chat_options_rename_fechacomentario_chat_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
